server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: after_route
          uri: lb://SERVICE-HI
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - RequestTime=false
            - StripPrefix=1
            - name: RequestRateLimiter
                args:
                  key-resolver: '#{@hostAddrKeyResolver}'
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 3
          predicates:
            - Path=/demo/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  redis:
    host: localhost
    port: 6379
